# Generated by Django 3.1.13 on 2021-09-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210930_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
