# Generated by Django 3.1.13 on 2021-09-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),
    ]
