# Generated by Django 3.1.13 on 2021-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210930_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='userdata',
            unique_together={('username', 'deleted')},
        ),
    ]
