# Generated by Django 3.1.13 on 2021-10-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagedata',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='languagedata',
            unique_together=set(),
        ),
    ]
