# Generated by Django 3.1.13 on 2021-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20211002_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagedata',
            name='code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='languagedata',
            unique_together={('code', 'deleted')},
        ),
    ]
