# Generated by Django 3.1.13 on 2021-10-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0003_auto_20211002_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagedata',
            unique_together=set(),
        ),
    ]
