# Generated by Django 3.1.13 on 2021-10-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20211002_1328'),
        ('lesson', '0002_auto_20211002_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondata',
            name='taught_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.languagedata'),
        ),
    ]
